### ISSUE TITLE
 Failed to apply plugin [id 'propdeps']

### ISSUE THREAD

**Issue by davidmoshal** [kukido/fitnesse-gradle-classpath#3]
17:58:40.098 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Creating new in-memory cache for repo 'maven' [11f4a460bd5f5c8d4de0569c8128391].
17:58:40.155 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting configuration :fitnesse-gradle-classpath:unspecified(classpath).
17:58:40.162 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency :fitnesse-gradle-classpath:unspecified(classpath) -> org.springframework.build.gradle:propdeps-plugin:0.0.1(dependency: org.springframework.build.gradle#propdeps-plugin;0.0.1 {classpath=[default]})
17:58:40.165 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version org.springframework.build.gradle:propdeps-plugin:0.0.1
17:58:40.165 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Attempting to resolve module 'org.springframework.build.gradle:propdeps-plugin:0.0.1' using repositories [maven]
17:58:40.179 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache module-metadata.bin (/Users/davem/.gradle/caches/modules-2/metadata-2.13/module-metadata.bin)
17:58:40.245 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.IvyXmlModuleDescriptorParser] post 1.3 ivy file: using exact as default matcher
17:58:40.262 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'org.springframework.build.gradle:propdeps-plugin:0.0.1' in 'maven'
17:58:40.265 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Using module 'org.springframework.build.gradle:propdeps-plugin:0.0.1' from repository 'maven'
17:58:40.268 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting configuration org.springframework.build.gradle:propdeps-plugin:0.0.1(default).
17:58:40.271 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.ResolvedConfigurationDependencyGraphVisitor] Attaching :fitnesse-gradle-classpath:unspecified(classpath) to its parents.
17:58:40.274 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.ResolvedConfigurationDependencyGraphVisitor] Attaching org.springframework.build.gradle:propdeps-plugin:0.0.1(default) to its parents.
17:58:40.285 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Flushing resolved configuration data in Binary store in /private/var/folders/gd/qgg5gjt90_n6dcywjrm3jccc0000gn/T/gradle6839827972093238881.bin. Wrote root :fitnesse-gradle-classpath:unspecified:classpath.
17:58:40.307 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache artifact-at-repository.bin (/Users/davem/.gradle/caches/modules-2/metadata-2.13/artifact-at-repository.bin)
17:58:40.312 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'org.springframework.build.gradle:propdeps-plugin:0.0.1:propdeps-plugin.jar' in resolver cache: /Users/davem/.gradle/caches/modules-2/files-2.1/org.springframework.build.gradle/propdeps-plugin/0.0.1/fe44c3b38db2f5169adfba91e1577eaf6d476948/propdeps-plugin-0.0.1.jar
17:58:40.320 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on no_buildscript class cache for build file '/Users/davem/Documents/literate-programming/fitness/fitnesse-gradle-classpath/build.gradle' (/Users/davem/.gradle/caches/2.1/scripts/build_7c6mbhdps5rk623vu5bppm2ffk/ProjectScript/no_buildscript).
17:58:40.321 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
17:58:41.478 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 1.779 secs
17:58:41.500 [ERROR] [org.gradle.BuildExceptionReporter]
17:58:41.501 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:58:41.503 [ERROR] [org.gradle.BuildExceptionReporter]
17:58:42.348 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
17:58:42.348 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/davem/Documents/literate-programming/fitness/fitnesse-gradle-classpath/build.gradle' line: 14
17:58:42.364 [ERROR] [org.gradle.BuildExceptionReporter]
17:58:42.365 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
17:58:42.365 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'fitnesse-gradle-classpath'.
17:58:42.366 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to apply plugin [id 'propdeps']
17:58:42.366 [ERROR] [org.gradle.BuildExceptionReporter]    > java.lang.String cannot be cast to org.gradle.api.artifacts.Configuration
17:58:42.366 [ERROR] [org.gradle.BuildExceptionReporter]
17:58:42.367 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
17:58:42.367 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
17:58:42.368 [LIFECYCLE] [org.gradle.BuildResultLogger]
17:58:42.369 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
17:58:42.369 [LIFECYCLE] [org.gradle.BuildResultLogger]
17:58:42.369 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 4.319 secs

**Comment by xubean** [comment]
Strangely enough, I started with the same problem. However, unlike you @davidmoshal I just changed the dependencies here: 

```
dependencies {
    classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.1
}
```

to 

```
dependencies {
    classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.7
}
```

and that worked. 
After rebuilding gradle and copying over the jar files as instructions, I end up with this error however:

```
java -jar fitnesse-standalone.jar -p 8080
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:286)
at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:239)
at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
at java.util.jar.JarVerifier.update(JarVerifier.java:228)
at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
at java.util.jar.JarFile.getInputStream(JarFile.java:415)
at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)
at sun.misc.Resource.cachedInputStream(Resource.java:77)
at sun.misc.Resource.getByteBuffer(Resource.java:160)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:191)
at fitnesse.PluginsLoader.forName(PluginsLoader.java:202)
at fitnesse.PluginsLoader.loadSymbolTypes(PluginsLoader.java:120)
at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:145)
at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:59)
at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:48)
at fitnesseMain.FitNesseMain.main(FitNesseMain.java:32) 
```

**Comment by twodarek** [comment]
Following @davidmoshal 's steps, I was still getting the following error:

```
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:286)
    at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:239)
    at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
    at java.util.jar.JarVerifier.update(JarVerifier.java:228)
    at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
    at java.util.jar.JarFile.getInputStream(JarFile.java:415)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)
    at sun.misc.Resource.cachedInputStream(Resource.java:77)
    at sun.misc.Resource.getByteBuffer(Resource.java:160)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forName(PropertyBasedPluginFeatureFactory.java:198)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachClass(PropertyBasedPluginFeatureFactory.java:143)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachObject(PropertyBasedPluginFeatureFactory.java:150)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.registerSymbolTypes(PropertyBasedPluginFeatureFactory.java:75)
    at fitnesse.plugins.PluginsLoader.loadSymbolTypes(PluginsLoader.java:83)
    at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:151)
    at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:65)
    at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:54)
    at fitnesseMain.FitNesseMain.main(FitNesseMain.java:34)
```

It turns out that Spring is signing jars and the java classloader didn't like the combined signatures.  I got around this by having the jar packaging step exclude signatures (VERY hacky, but I'm in the middle of a hack-a-thon, so meh).  Here's the updated build.gradle that excludes signatures:

```
buildscript {
    repositories {
        maven { url 'http://repo.springsource.org/plugins-release' }
        flatDir {
            dirs 'lib'
        }
    }
    dependencies {
        classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.8-SNAPSHOT'
    }
}

apply plugin: 'java'
apply plugin: 'findbugs'

configure(allprojects) {
    apply plugin: 'propdeps'
}

repositories {
    maven {
        url 'http://repo.gradle.org/gradle/libs-releases-local'
    }
    mavenCentral()
}

dependencies {
    compile 'org.gradle:gradle-tooling-api:1.6'
    provided 'org.fitnesse:fitnesse:20150226'
    testCompile 'junit:junit:4.11'
}

jar {
    from (configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }) {
        // remove all signature files
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
}
```
